#include "/Engine/Public/Platform.ush"
#include "VoxelPixelShader.usf"
#include "/VertexFactoryShaders/VoxelVertexFactory.ush"

struct VS_OUTPUT
{
    float4 Position : SV_POSITION;
};

struct FInput
{
    float3 Position : ATTRIBUTE0;
    float3 Normal : ATTRIBUTE1;
    //uint VertexId : SV_VertexID;
};

VS_OUTPUT MainVS(FInput input)
{
    VS_OUTPUT output;
    output.Position = float4(input.Position,1);
    return output;
}
