#include "/Engine/Public/Platform.ush"

struct VS_INPUT
{
    float3 Position : ATTRIBUTE0;
    float3 Normal : ATTRIBUTE1;
};

struct VS_OUTPUT
{
    float4 Position : SV_POSITION;
    float3 Normal : TEXCOORD0;
};

cbuffer Parameters
{
    float4x4 ModelViewProjection;
};

VS_OUTPUT MainVS(VS_INPUT Input)
{
    VS_OUTPUT Output;
    Output.Position = mul(ModelViewProjection, float4(Input.Position, 1.0));
    Output.Normal = Input.Normal;
    return Output;
}